---
- name: Ensure only specified DNS servers are in resolv.conf
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    mode: '0644'
    content: |
      {% for dns in dns_servers %}
      nameserver {{ dns }}
      {% endfor %}
